runtime: nodejs10

handlers:
  - url: /
    static_files: client/build/index.html
    upload: client/build/index.html
  - url: /(.*)
    static_files: client/build/\1
    upload: client/build/(.*)

includes:
  - env_variables.yaml
